### ISSUE TITLE
login should not create a new session if already logged in

### ISSUE THREAD

**Issue by steebchen** [robojones/graphql#3]

**Comment by robojones** [comment]
We could return the same session when the user is already logged in. Alternatively an error can be returned. Which is the better solution?

**Comment by robojones** [comment]
If we return the same session we will have to verify if there is a session token in the context and then query the session from the DB.

I would prefer not to add that new complexity to the login method.
https://github.com/robojones/graphql/blob/c0ba16e92ec4ba2d28fa7e4321afb7ec24e1c539/api/resolver/mutation/auth/login.go#L26

Thinking about it I am not sure anymore if this is even an issue... It can be easily be verified if a user is logged in on the client side before using the login mutation. If he visits the login page and is already logged in he could just be redirected to the dashboard without any API call.

**Comment by steebchen** [comment]
sounds good
